#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

MUNIN_PLUGINS="
	pdns_errors
	pdns_latency
	pdns_queries
	pdns_queue_size
"

echo "* Activate munin plugins"
/opt/qutic/bin/munin-node-plugins ${MUNIN_PLUGINS}

# Configuring image specific packages
echo "* Configuring image specific packages.";

groupadd -g 1101 pdns
useradd -m -s /usr/bin/bash -d /var/lib/pdns -u 1101 -g pdns pdns
passwd -N pdns
passwd -d pdns
chmod 0640 /opt/qutic/libexec/.env
chown root:pdns /opt/qutic/libexec/.env
mkdir -p /var/lib/pdns
chown pdns:pdns /var/lib/pdns

echo "* fix dnsdist smf"
sed -i \
  's#<property_group name="dnsdist" type="application">#<property_group name="application" type="application">#' \
  /opt/local/lib/svc/manifest/dnsdist.xml
svccfg import /opt/local/lib/svc/manifest/dnsdist.xml

echo "* fix pdns rights"
chown -R pdns:pdns /var/run/pdns
chown root:pdns /opt/local/etc/pdns.conf
chmod 0640 /opt/local/etc/pdns.conf
chown -R pdns:pdns /opt/local/lib/pdns/

# echo "* enable pdns services"
# svcadm enable svc:/pkgsrc/pdns:default
# svcadm enable svc:/pkgsrc/dnsdist:default
# svcadm enable svc:/pkgsrc/pdns-recursor:default

echo "* enable firewall"
svcadm enable svc:/network/ipfilter:default

# create log file
mkdir -p /var/log/pdns/
touch /var/log/pdns/pdns.log
chown -R pdns:pdns /var/log/pdns/

echo "* install ruby gems"
gem install dotenv || true
gem install sequel || true

echo "* add stub my.cnf file"
touch /root/.my.cnf
chmod 0400 /root/.my.cnf

# Clean up
echo "* Cleaning up."
rm /root/customize

# Prepare image for provisioning
sm-prepare-image -y
