#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

MUNIN_PLUGINS="
	pdns_errors
	pdns_latency
	pdns_queries
	pdns_queue_size
"

echo "* Activate munin plugins"
/opt/qutic/bin/munin-node-plugins ${MUNIN_PLUGINS}

# Configuring image specific packages
echo "* Configuring image specific packages.";

groupadd -g 1101 pdns
useradd -u 1101 -g pdns pdns

echo "* fix dnsdist smf"
sed -i 's#<property_group name="dnsdist" type="application">#<property_group name="application" type="application">#' \
  /opt/local/lib/svc/manifest/dnsdist.xml

svccfg import /opt/local/lib/svc/manifest/dnsdist.xml

echo "* enable pdns"
svcadm enable svc:/pkgsrc/pdns:default
svcadm enable svc:/pkgsrc/dnsdist:default
#svcadm enable svc:/pkgsrc/pdns-recursor:default

# create log file
touch /var/log/pdns.log

echo "* add stub my.cnf file"
touch /root/.my.cnf
chmod 0400 /root/.my.cnf

# Clean up
echo "* Cleaning up."
rm /root/customize

# Prepare image for provisioning
sm-prepare-image -y
