#!/usr/bin/env ruby

require 'rubygems'
require 'mysql2'
require 'sequel'
require 'dotenv'
Dotenv.load

begin
  DB = Sequel.connect(
    adapter:  'mysql2',
    user:     ENV['MYSQL_USER'],
    host:     ENV['MYSQL_HOST'],
    database: ENV['MYSQL_DATABASE'],
    password: ENV['MYSQL_PWD']
  )
rescue Exception => e
  STDERR.puts "ERROR: failed to connect to Database!"
  exit 1
end

domains = DB[:domains].where(type: 'MASTER').all

domains.each do |domain|
  puts "Updating serial on domain: #{domain[:name]}"
  %x[/opt/local/bin/pdnsutil increase-serial #{domain[:name]}]
  %x[/opt/local/bin/pdns_control notify #{domain[:name]}]end
