#!/sbin/sh
#
# $NetBSD: spiped.sh,v 1.2 2014/08/18 22:19:16 wiedi Exp $
#
# Init script for spiped.
#

. /lib/svc/share/smf_include.sh

/opt/local/bin/dnsdist -u dnsdist \
                       -g dnsdist \
                       -C /opt/local/etc/dnsdist.conf \
                       --supervised &

exit $SMF_EXIT_OK
